import { accessoriesOne, accessoriesTwo, accessoriesThree, accessoriesFour, accessoriesFive, accessoriesSix, accessoriesSeven, boyOne, boyTwo, boyThree, boyFour, boyFive, girlOne, girlTwo, girlThree, girlFour } from '../constant/productImg'

export const productsAcc = [
    {
        title: "Buddha Bracelet",
        img: { accessoriesOne },
        type: "accessories",
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        quantity: 0,
        stars: 4.5,
        oldPrize: "0",
        newPrize: "$150.00",
    },
    {
        title: "Bright Gold Purse With Chain",
        img: { accessoriesTwo },
        type: "accessories, girl",
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        quantity: 0,
        stars: 4,
        oldPrize: "0",
        newPrize: "$150.00",
    },
    {
        title: "Black Over-the-shoulder Handbag",
        img: { accessoriesThree },
        type: "accessories, girl",
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        quantity: 0,
        stars: 4.5,
        oldPrize: "0",
        newPrize: "$150.00",
    },
    {
        title: "Anchor Bracelet",
        img: { accessoriesFour },
        type: "accessories",
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        quantity: 0,
        stars: 4.5,
        oldPrize: "$180.00",
        newPrize: "$150.00",
    },
    {
        title: "Light Brown Purse",
        img: { accessoriesFive },
        type: "accessories, girl",
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        quantity: 0,
        stars: 3.5,
        oldPrize: "0",
        newPrize: "$150.00",
    },
    {
        title: "Bright Red Bag",
        img: { accessoriesSix },
        type: "accessories, girl",
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        quantity: 0,
        stars: 4.5,
        oldPrize: "0",
        newPrize: "$140.00",
    },
    {
        title: "Boho Bangle Bracelet",
        img: { accessoriesSeven },
        type: "accessories",
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        quantity: 0,
        stars: 4.5,
        oldPrize: "0",
        newPrize: "$170.00",
    },


]

export const productsBoy = [
    {
        title: "Black Hoodie",
        img: { boyOne },
        type: "boy",
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        quantity: 0,
        stars: 4,
        oldPrize: "0",
        newPrize: "$150.00",
    },
    {
        title: "DNK Yellow Shoes",
        img: { boyTwo },
        type: "boy",
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        quantity: 0,
        stars: 4.5,
        oldPrize: "$150.00",
        newPrize: "$120.00",
    },
    {
        title: "Blue Hoodie",
        img: { boyThree },
        type: "boy",
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        quantity: 0,
        stars: 4.5,
        oldPrize: "0",
        newPrize: "$150.00",
    },
    {
        title: "Dark Blue Denim Jeans",
        img: { boyFour },
        type: "boy",
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        quantity: 0,
        stars: 4,
        oldPrize: "0",
        newPrize: "$150.00",
    },
    {
        title: "Dark Brown Jeans",
        img: { boyFive },
        type: "boy",
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        quantity: 0,
        stars: 4.5,
        oldPrize: "0",
        newPrize: "$150.00",
    },
]

export const productsGirl = [
    {
        title: "Blue Denim Shorts",
        img: { girlOne },
        type: "girl",
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        quantity: 0,
        stars: 4.5,
        oldPrize: "$150.00",
        newPrize: "$130.00",
    },
    {
        title: "Blue Denim Jeans",
        img: { girlTwo },
        type: "girl",
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        quantity: 0,
        stars: 3.5,
        oldPrize: "0",
        newPrize: "$150.00",
    },
    {
        title: "Basic Gray Jeans",
        img: { girlThree },
        type: "girl",
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        quantity: 0,
        stars: 4.5,
        oldPrize: "0",
        newPrize: "$150.00",
    },
    {
        title: "Blue Tshirt",
        img: { girlFour },
        type: "girl",
        description: "Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.",
        quantity: 0,
        stars: 4.5,
        oldPrize: "$28.00",
        newPrize: "$25.00",
    },
]

export const originalProduct = productsBoy.concat(productsAcc, productsGirl);